name: Release

on:
  push:
    tags:
      - "v*.*"
      - "v*.*.*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Packer Build
    uses: ./.github/workflows/call-packer.yml
    secrets: inherit
    with:
      deploy: true
